_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 1
                - 2
                - 3
                - 14
                - 23
                - 24
                - 55
            "4": 3.10.15
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 32
data_aug:
    value: false
data_dir:
    value: data/inaturalist_12K
dense_size:
    value: 1024
dropout:
    value: 0
early_stopping_patience:
    value: 3
epochs:
    value: 5
freeze_option:
    value: 2
lr:
    value: 0.0007805776614008136
scheduler_patience:
    value: 4
use_scheduler:
    value: false
weight_decay:
    value: 0.001
