wandb_version: 1

activation:
  value: tanh
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.3
early_stopping_patience:
  value: 5
epochs:
  value: 5
filter_sizes:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
lr:
  value: 0.0001
num_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
optimizer:
  value: adam
scheduler_patience:
  value: 2
use_data_augmentation:
  value: false
use_scheduler:
  value: false
weight_decay:
  value: 0.001
