wandb_version: 1

activation:
  value: silu
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.4
early_stopping_patience:
  value: 7
epochs:
  value: 5
filter_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
lr:
  value: 0.0005
num_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
optimizer:
  value: adam
scheduler_patience:
  value: 3
use_data_augmentation:
  value: true
use_scheduler:
  value: false
weight_decay:
  value: 0.001
