wandb_version: 1

activation:
  value: mish
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.3
early_stopping_patience:
  value: 7
epochs:
  value: 15
filter_sizes:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
lr:
  value: 0.0005
num_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
optimizer:
  value: sgd
scheduler_patience:
  value: 2
use_data_augmentation:
  value: true
use_scheduler:
  value: true
weight_decay:
  value: 0.0001
