wandb_version: 1

activation:
  value: relu
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.2
early_stopping_patience:
  value: 5
epochs:
  value: 15
filter_sizes:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
lr:
  value: 0.0005
num_filters:
  value:
  - 16
  - 32
  - 64
  - 64
  - 128
optimizer:
  value: sgd
scheduler_patience:
  value: 3
use_data_augmentation:
  value: true
use_scheduler:
  value: true
weight_decay:
  value: 0.0001
