wandb_version: 1

activation:
  value: relu
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.2
early_stopping_patience:
  value: 7
epochs:
  value: 15
filter_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
lr:
  value: 0.0001
num_filters:
  value:
  - 16
  - 32
  - 64
  - 64
  - 128
optimizer:
  value: adam
scheduler_patience:
  value: 2
use_data_augmentation:
  value: true
use_scheduler:
  value: false
weight_decay:
  value: 0.0001
