wandb_version: 1

activation:
  value: tanh
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.3
early_stopping_patience:
  value: 5
epochs:
  value: 5
filter_sizes:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
lr:
  value: 0.0005
num_filters:
  value:
  - 16
  - 32
  - 64
  - 64
  - 128
optimizer:
  value: adam
scheduler_patience:
  value: 2
use_data_augmentation:
  value: true
use_scheduler:
  value: false
weight_decay:
  value: 0.001
