wandb_version: 1

activation:
  value: silu
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.3
early_stopping_patience:
  value: 5
epochs:
  value: 15
filter_sizes:
  value:
  - 3
  - 3
  - 5
  - 5
  - 7
lr:
  value: 0.0001
num_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
optimizer:
  value: adam
scheduler_patience:
  value: 4
use_data_augmentation:
  value: false
use_scheduler:
  value: true
weight_decay:
  value: 0.0001
