### ✅ `config.yaml`

method: bayes
metric:
  name: val_acc
  goal: maximize
parameters:
  lr:
    values: [0.01, 0.001, 0.0001]
  batch_size:
    values: [32, 64]
  dropout:
    values: [0.3, 0.5, 0.6]
  activation:
    values: ["relu", "tanh"]
  optimizer:
    values: ["adam", "sgd"]
  num_filters:
    values:
      - [32, 64, 128, 128, 256]
      - [16, 32, 64, 64, 128]
