wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0
early_stopping_patience:
  value: 7
epochs:
  value: 10
freeze_option:
  value: 2
lr:
  value: 0.00037687205772976736
scheduler_patience:
  value: 2
use_scheduler:
  value: true
weight_decay:
  value: 0.001
