wandb_version: 1

batch_size:
  value: 32
data_aug:
  value: true
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 512
dropout:
  value: 0.2
early_stopping_patience:
  value: 3
epochs:
  value: 5
freeze_option:
  value: 1
lr:
  value: 0.000322155317448624
scheduler_patience:
  value: 2
use_scheduler:
  value: true
weight_decay:
  value: 0.0001
