wandb_version: 1

batch_size:
  value: 32
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0.1
early_stopping_patience:
  value: 5
epochs:
  value: 15
freeze_option:
  value: 0
lr:
  value: 5.40352792491126e-05
scheduler_patience:
  value: 2
use_scheduler:
  value: true
weight_decay:
  value: 0.001
