wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 1024
dropout:
  value: 0.2
early_stopping_patience:
  value: 7
epochs:
  value: 10
freeze_option:
  value: 2
lr:
  value: 9.11428880261996e-05
scheduler_patience:
  value: 4
use_scheduler:
  value: true
weight_decay:
  value: 0
