wandb_version: 1

batch_size:
  value: 32
data_aug:
  value: true
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 512
dropout:
  value: 0.1
early_stopping_patience:
  value: 3
epochs:
  value: 15
freeze_option:
  value: 0
lr:
  value: 0.0006689995827895591
scheduler_patience:
  value: 4
use_scheduler:
  value: true
weight_decay:
  value: 0.0001
