wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 512
dropout:
  value: 0
early_stopping_patience:
  value: 7
epochs:
  value: 5
freeze_option:
  value: 2
lr:
  value: 0.0007377681034243883
scheduler_patience:
  value: 3
use_scheduler:
  value: true
weight_decay:
  value: 0.0001
