wandb_version: 1

batch_size:
  value: 32
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0
early_stopping_patience:
  value: 3
epochs:
  value: 10
freeze_option:
  value: 2
lr:
  value: 0.0005556504614335408
scheduler_patience:
  value: 4
use_scheduler:
  value: true
weight_decay:
  value: 0.001
