wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: true
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 1024
dropout:
  value: 0
early_stopping_patience:
  value: 7
epochs:
  value: 5
freeze_option:
  value: 1
lr:
  value: 0.00022513602751211953
scheduler_patience:
  value: 2
use_scheduler:
  value: true
weight_decay:
  value: 0.001
