wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: true
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0.2
early_stopping_patience:
  value: 7
epochs:
  value: 15
freeze_option:
  value: 2
lr:
  value: 0.0008071297260192423
scheduler_patience:
  value: 4
use_scheduler:
  value: true
weight_decay:
  value: 0
