wandb_version: 1

batch_size:
  value: 32
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 1024
dropout:
  value: 0
early_stopping_patience:
  value: 7
epochs:
  value: 15
freeze_option:
  value: 1
lr:
  value: 0.0005964031972470177
scheduler_patience:
  value: 4
use_scheduler:
  value: true
weight_decay:
  value: 0.0001
