wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0.1
early_stopping_patience:
  value: 7
epochs:
  value: 5
freeze_option:
  value: 0
lr:
  value: 0.0009282434029548596
scheduler_patience:
  value: 3
use_scheduler:
  value: true
weight_decay:
  value: 0.0001
