wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: true
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 1024
dropout:
  value: 0.2
early_stopping_patience:
  value: 5
epochs:
  value: 15
freeze_option:
  value: 1
lr:
  value: 9.38938618428379e-05
scheduler_patience:
  value: 4
use_scheduler:
  value: false
weight_decay:
  value: 0
