wandb_version: 1

batch_size:
  value: 32
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 1024
dropout:
  value: 0
early_stopping_patience:
  value: 3
epochs:
  value: 5
freeze_option:
  value: 2
lr:
  value: 0.0007805776614008136
scheduler_patience:
  value: 4
use_scheduler:
  value: false
weight_decay:
  value: 0.001
