wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0
early_stopping_patience:
  value: 7
epochs:
  value: 5
freeze_option:
  value: 0
lr:
  value: 4.348390112296065e-05
scheduler_patience:
  value: 4
use_scheduler:
  value: false
weight_decay:
  value: 0.001
