wandb_version: 1

batch_size:
  value: 32
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0.2
early_stopping_patience:
  value: 7
epochs:
  value: 15
freeze_option:
  value: 0
lr:
  value: 0.00018876450670648543
scheduler_patience:
  value: 3
use_scheduler:
  value: false
weight_decay:
  value: 0
