wandb_version: 1

batch_size:
  value: 32
data_aug:
  value: true
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0
early_stopping_patience:
  value: 7
epochs:
  value: 15
freeze_option:
  value: 2
lr:
  value: 4.967190955926913e-05
scheduler_patience:
  value: 3
use_scheduler:
  value: false
weight_decay:
  value: 0
