wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: true
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 512
dropout:
  value: 0
early_stopping_patience:
  value: 7
epochs:
  value: 10
freeze_option:
  value: 2
lr:
  value: 6.615441503031478e-05
scheduler_patience:
  value: 2
use_scheduler:
  value: true
weight_decay:
  value: 0
