wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: true
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0
early_stopping_patience:
  value: 3
epochs:
  value: 15
freeze_option:
  value: 1
lr:
  value: 0.0002040767043312547
scheduler_patience:
  value: 4
use_scheduler:
  value: false
weight_decay:
  value: 0.0001
