wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: true
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0.2
early_stopping_patience:
  value: 5
epochs:
  value: 15
freeze_option:
  value: 1
lr:
  value: 0.00011467720178547124
scheduler_patience:
  value: 2
use_scheduler:
  value: true
weight_decay:
  value: 0
