wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: false
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 256
dropout:
  value: 0.2
early_stopping_patience:
  value: 7
epochs:
  value: 10
freeze_option:
  value: 2
lr:
  value: 9.316694342791374e-05
scheduler_patience:
  value: 2
use_scheduler:
  value: false
weight_decay:
  value: 0.001
