wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: true
data_dir:
  value: data/inaturalist_12K
dense_size:
  value: 1024
dropout:
  value: 0
early_stopping_patience:
  value: 5
epochs:
  value: 15
freeze_option:
  value: 2
lr:
  value: 1.4545980796923787e-05
scheduler_patience:
  value: 3
use_scheduler:
  value: true
weight_decay:
  value: 0
