wandb_version: 1

activation:
  value: mish
batch_norm:
  value: false
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.4
early_stopping_patience:
  value: 3
epochs:
  value: 5
filter_sizes:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
lr:
  value: 0.0005
num_filters:
  value:
  - 16
  - 32
  - 64
  - 64
  - 128
optimizer:
  value: sgd
scheduler_patience:
  value: 4
use_data_augmentation:
  value: true
use_scheduler:
  value: false
weight_decay:
  value: 0.001
