wandb_version: 1

activation:
  value: tanh
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.2
early_stopping_patience:
  value: 5
epochs:
  value: 5
filter_sizes:
  value:
  - 5
  - 5
  - 5
  - 5
  - 5
lr:
  value: 0.0001
num_filters:
  value:
  - 16
  - 32
  - 64
  - 64
  - 128
optimizer:
  value: sgd
scheduler_patience:
  value: 3
use_data_augmentation:
  value: true
use_scheduler:
  value: false
weight_decay:
  value: 0.001
