wandb_version: 1

activation:
  value: tanh
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.2
early_stopping_patience:
  value: 7
epochs:
  value: 10
filter_sizes:
  value:
  - 7
  - 7
  - 7
  - 7
  - 7
lr:
  value: 0.0001
num_filters:
  value:
  - 16
  - 32
  - 64
  - 64
  - 128
optimizer:
  value: sgd
scheduler_patience:
  value: 2
use_data_augmentation:
  value: true
use_scheduler:
  value: true
weight_decay:
  value: 0.001
