wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.3
early_stopping_patience:
  value: 7
epochs:
  value: 15
filter_sizes:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
lr:
  value: 0.0005
num_filters:
  value:
  - 16
  - 32
  - 64
  - 64
  - 128
optimizer:
  value: sgd
scheduler_patience:
  value: 3
use_data_augmentation:
  value: true
use_scheduler:
  value: false
weight_decay:
  value: 0.0001
