_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
activation:
    value: relu
batch_norm:
    value: false
batch_size:
    value: 32
data_dir:
    value: data
dense_neurons:
    value: 512
dropout:
    value: 0.3
epochs:
    value: 10
filter_sizes:
    value:
        - 3
        - 3
        - 3
        - 3
        - 3
lr:
    value: 0.001
num_classes:
    value: 10
num_filters:
    value:
        - 16
        - 32
        - 64
        - 64
        - 128
optimizer:
    value: sgd
use_wandb:
    value: true
wandb_project:
    value: cnn_from_scratch_project
weight_decay:
    value: 0.0001
