_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 100
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 100
            "3":
                - 1
                - 2
                - 3
                - 14
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
activation:
    value: tanh
batch_norm:
    value: true
batch_size:
    value: 64
data_dir:
    value: data/inaturalist_12K
dense_neurons:
    value: 512
dropout:
    value: 0.3
early_stopping_patience:
    value: 7
epochs:
    value: 10
filter_sizes:
    value:
        - 3
        - 3
        - 5
        - 5
        - 7
lr:
    value: 0.0005
num_filters:
    value:
        - 32
        - 64
        - 128
        - 128
        - 256
optimizer:
    value: sgd
scheduler_patience:
    value: 2
use_data_augmentation:
    value: true
use_scheduler:
    value: true
use_wandb:
    value: true
wandb_project:
    value: cnn_from_scratch_project
weight_decay:
    value: 0.0001
