wandb_version: 1

activation:
  value: silu
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.3
early_stopping_patience:
  value: 3
epochs:
  value: 10
filter_sizes:
  value:
  - 7
  - 5
  - 5
  - 3
  - 3
lr:
  value: 0.0001
num_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
optimizer:
  value: sgd
scheduler_patience:
  value: 4
use_data_augmentation:
  value: true
use_scheduler:
  value: false
weight_decay:
  value: 0.0001
