wandb_version: 1

activation:
  value: silu
batch_norm:
  value: false
batch_size:
  value: 32
dense_neurons:
  value: 512
dropout:
  value: 0.3
early_stopping_patience:
  value: 5
epochs:
  value: 5
filter_sizes:
  value:
  - 7
  - 7
  - 7
  - 7
  - 7
lr:
  value: 0.0001
num_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
optimizer:
  value: sgd
scheduler_patience:
  value: 3
use_data_augmentation:
  value: false
use_scheduler:
  value: false
weight_decay:
  value: 0.0001
