wandb_version: 1

activation:
  value: mish
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 256
dropout:
  value: 0.2
early_stopping_patience:
  value: 7
epochs:
  value: 5
filter_sizes:
  value:
  - 3
  - 3
  - 5
  - 5
  - 7
lr:
  value: 0.0005
num_filters:
  value:
  - 16
  - 32
  - 64
  - 64
  - 128
optimizer:
  value: adam
scheduler_patience:
  value: 2
use_data_augmentation:
  value: true
use_scheduler:
  value: true
weight_decay:
  value: 0.0001
