wandb_version: 1

activation:
  value: mish
batch_norm:
  value: false
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.2
early_stopping_patience:
  value: 3
epochs:
  value: 10
filter_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
lr:
  value: 0.0005
num_filters:
  value:
  - 16
  - 32
  - 64
  - 64
  - 128
optimizer:
  value: sgd
scheduler_patience:
  value: 4
use_data_augmentation:
  value: false
use_scheduler:
  value: true
weight_decay:
  value: 0.0001
