wandb_version: 1

activation:
  value: tanh
batch_norm:
  value: true
batch_size:
  value: 64
dense_neurons:
  value: 512
dropout:
  value: 0.2
early_stopping_patience:
  value: 7
filter_sizes:
  value:
  - 3
  - 3
  - 3
  - 3
  - 3
lr:
  value: 0.0005
num_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
optimizer:
  value: adam
scheduler_patience:
  value: 3
use_data_augmentation:
  value: true
use_scheduler:
  value: true
weight_decay:
  value: 0.001
