wandb_version: 1

activation:
  value: relu
batch_norm:
  value: true
batch_size:
  value: 32
dense_neurons:
  value: 256
dropout:
  value: 0.2
early_stopping_patience:
  value: 5
filter_sizes:
  value:
  - 7
  - 7
  - 7
  - 7
  - 7
lr:
  value: 0.0005
num_filters:
  value:
  - 32
  - 64
  - 128
  - 128
  - 256
optimizer:
  value: adam
scheduler_patience:
  value: 4
use_data_augmentation:
  value: true
use_scheduler:
  value: true
weight_decay:
  value: 0.001
