wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dense_neurons:
  value: 1024
dropout:
  value: 0.5
lr:
  value: 0.008788478212560054
num_filters:
  value:
  - 16
  - 32
  - 64
  - 128
  - 128
optimizer:
  value: sgd
